version: '3.8'


services:
  db:
    container_name: db-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest

    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=admin@SqlServerDocker2025
    networks:
      - api-network
    volumes:
      - db_data:/var/opt/mssql

  api_backend: 
    container_name: api

    build: 
      context: ../Estacionamento
      dockerfile: ./Dockerfile

    networks:
      - api-network

    depends_on:
      - db

volumes:
  db_data:
    driver: local

networks:
  api-network:
    driver: bridge