FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src

COPY Estacionamento.Api/Estacionamento.Api.csproj Estacionamento.Api/
COPY Estacionamento.Domain/Estacionamento.Domain.csproj Estacionamento.Domain/
COPY Estacionamento.Data/Estacionamento.Data.csproj Estacionamento.Data/
COPY Estacionamento.Tests/Estacionamento.Tests.csproj Estacionamento.Tests/
COPY Estacionamento.sln .

RUN dotnet restore Estacionamento.sln

COPY . .

WORKDIR /src/Estacionamento.Tests
RUN dotnet test .

# Copia o resto do código
COPY . .

# Entrypoint muda no docker-compose (dotnet watch run), então aqui basta:
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:80", "--project", "Estacionamento.Api"]

