@Estacionamento.Api_HostAddress = http://localhost:8080

GET {{Estacionamento.Api_HostAddress}}/proprietario/
Accept: application/json
###

GET {{Estacionamento.Api_HostAddress}}/proprietario/1b74c796-232c-4c1f-8beb-310760d5e0ba
Accept: application/json
###

GET {{Estacionamento.Api_HostAddress}}/veiculo/
Accept: application/json
###
